#! /bin/sh

ip=`hostname -i`

while :
do
	json="{\"country\":\"${2}\",\"ip\":\"${ip}\"}"
	curl  -H "Content-type: aation/json" -X POST -d "${json}" $1/
	random=`od -vAn --width=4 -tu4 -N4 </dev/urandom`
	random=$(($random % 3))
	sleep $random
done
